### PR TITLE
CAN YOU TAKE ME HIGHER?

### PR DESCRIPTION
**Pull request by SamSamskies**

### CODE REVIEW

**Comment by utxo-one** [comment]
Concerned there is is no 🍦 anywhere in your commit

**Comment by SamSamskies** [comment]
my ice cream so good zapper doesn't work on github 🙁

**Comment by SamSamskies** [comment]
video can be previewed here 😂
https://njump.me/nevent1qqsq7yvn00nnq8envst3tx2ccjfsaphleupjt6wuc4v5p93wgxjspwqprpmhxue69uhhyetvv9ujumn0wdmksetjv5hxxmmdqgsxqn5kuzvex6ssfzpetzcypdrkwts0qjxf3tre8umllex8yqneavs7xwz2y

**Comment by utxo-one** [comment]
Approved

**Comment by corndalorian** [comment]
Let's make this happen 👀🚀

**Pull request merged**
